### ISSUE TITLE
JavaScript Setting Opacity on /checkout/onepage/success/

### ISSUE THREAD

**Issue by pinehurstcoins** [bitpay/bitpay-checkout-magento#10]
There is a JS file that is setting the container with the main class to 0.3 opacity:

```
if(window.location.pathname == '/checkout/onepage/success/' && getCookie('flow') !== -1){
    $j(".main").css('opacity','0.3')
    showModal(getCookie('env'))
}
```
This is firing for all payment methods. 

Also, Bitpay isn't creating any transaction in the Order View

**Comment by thejoshualewis** [comment]
Thanks for letting us know, this is fixed in the latest release
https://github.com/bitpay/bitpay-checkout-magento/releases/tag/v3.0.6

**Comment by pinehurstcoins** [comment]
Sure anytime. Thanks for updating it!

Tal Sneed

Project Manager

Pinehurst Coins


(910)235-2646


T.sneed@PinehurstCoins.com <http://t.sneed@pinehurstcoins.com/>[email]

www.PinehurstCoins.com  <http://www.pinehurstcoins.com/>[website]

Facebook <https://www.facebook.com/pinehurstcoins/>




NOTICE: The information contained in this communication is confidential, is
intended only for the use of the recipient(s) named above, and may be
legally privileged. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution, or
copying of this communication, or any of its attachments, is strictly
prohibited. If you have received this communication in error, please notify
the sender immediately and destroy the original message.
